Add 'tiny' as init
iegomez/mosquitto-go-auth pull request #178
Opened 2021-06-02 12:03 UTC by kfdm

A lot of containers try to avoid using `shell` for the ENTRYPOINT due to issues with escaping characters and not always handling signals very well. Many use [tiny](https://github.com/krallin/tini#why-tini) as a way to handle this.

This is configured so that it is also easy to replace CMD with your own value without affecting the init.

2021-06-02 13:47 UTC, iegomez requested changes

2021-06-02 13:47 UTC, iegomez commented on Dockerfile
> +RUN apt-get update && apt-get install -y libwebsockets8 libc-ares2 openssl uuid tini
```suggestion
RUN apt-get update && apt-get install -y libwebsockets8 libc-ares2 openssl uuid tiny
```

2021-06-02 13:48 UTC, iegomez commented
@kfdm There's a typo that needs changing.
I don't know `tiny`, I'll look it up when I get some time before further reviewing.

2021-06-02 16:35 UTC, iegomez commented on Dockerfile
> +RUN apt-get update && apt-get install -y libwebsockets8 libc-ares2 openssl uuid tini
Ha, sorry, the typo is the other way around.

2021-06-02 16:35 UTC, iegomez requested changes

2021-06-02 16:35 UTC, iegomez commented on docker/Dockerfile
> +RUN apt-get update && apt-get install -y libwebsockets8 libc-ares2 openssl uuid tiny
```suggestion
RUN apt-get update && apt-get install -y libwebsockets8 libc-ares2 openssl uuid tini
```

2021-06-02 23:54 UTC, kfdm commented
Woops, sorry about the typo there. I likely only tested the base Docker image and neglected to test the other one 🙇 
Should be fixed now.

This should explain things in detail https://github.com/krallin/tini/issues/8#issuecomment-146135930

2021-06-03 17:26 UTC, iegomez approved these changes

2021-06-03 23:00 UTC, merged